// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, created_at, updated_at, user_id, amount, transaction_type, category, description, party, transaction_date)
VALUES (
    gen_random_uuid(),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, updated_at, user_id, amount, transaction_type, category, description, party, transaction_date
`

type CreateTransactionParams struct {
	UserID          uuid.UUID
	Amount          decimal.Decimal
	TransactionType TransactionTypeEnum
	Category        sql.NullString
	Description     sql.NullString
	Party           sql.NullString
	TransactionDate time.Time
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Category,
		arg.Description,
		arg.Party,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Category,
		&i.Description,
		&i.Party,
		&i.TransactionDate,
	)
	return i, err
}
