// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, created_at, updated_at, user_id, amount, transaction_type, category, description, party, transaction_date)
VALUES (
    gen_random_uuid(),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, updated_at, user_id, amount, transaction_type, category, description, party, transaction_date, deleted_at
`

type CreateTransactionParams struct {
	UserID          uuid.UUID
	Amount          decimal.Decimal
	TransactionType TransactionTypeEnum
	Category        sql.NullString
	Description     sql.NullString
	Party           sql.NullString
	TransactionDate time.Time
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Category,
		arg.Description,
		arg.Party,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Category,
		&i.Description,
		&i.Party,
		&i.TransactionDate,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :one
UPDATE transactions 
SET deleted_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND id = $2
RETURNING id, created_at, updated_at, user_id, amount, transaction_type, category, description, party, transaction_date, deleted_at
`

type DeleteTransactionParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, deleteTransaction, arg.UserID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Category,
		&i.Description,
		&i.Party,
		&i.TransactionDate,
		&i.DeletedAt,
	)
	return i, err
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT id, created_at, updated_at, user_id, amount, transaction_type, category, description, party, transaction_date, deleted_at FROM transactions WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserTransactions(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Amount,
			&i.TransactionType,
			&i.Category,
			&i.Description,
			&i.Party,
			&i.TransactionDate,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactionsForPeriod = `-- name: GetUserTransactionsForPeriod :many
SELECT id, created_at, updated_at, user_id, amount, transaction_type, category, description, party, transaction_date, deleted_at FROM transactions WHERE user_id = $1 AND deleted_at IS NULL and transaction_date <= $2 and transaction_date >= $3
`

type GetUserTransactionsForPeriodParams struct {
	UserID            uuid.UUID
	TransactionDate   time.Time
	TransactionDate_2 time.Time
}

func (q *Queries) GetUserTransactionsForPeriod(ctx context.Context, arg GetUserTransactionsForPeriodParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getUserTransactionsForPeriod, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Amount,
			&i.TransactionType,
			&i.Category,
			&i.Description,
			&i.Party,
			&i.TransactionDate,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
